SERVICE_GROUP_ROOT=$BUILD_SOURCESDIRECTORY/ARO.Pipelines/ev2/Support/Geneva-Actions-Deploy/ServiceGroupRoot

mkdir $OB_OUTPUTDIRECTORY

cp -r $SERVICE_GROUP_ROOT $OB_OUTPUTDIRECTORY/ServiceGroupRoot/
